services:
  mlflow:
    env_file:
      - .env.mlflow.dev
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5001"
    volumes:
      - ./db:/db
      - ./data/artifacts:/data/artifacts
    networks:
      - app-network
  mage:
    env_file:
      - .env.mage.dev
    build:
      context: .
      dockerfile: Dockerfile.mage
    ports:
      - 6789:6789
    volumes:
      - ./data/mage_data:/home/src/mage_data
      - ./hate_speech_detector:/home/src/hate_speech_detector
      - ./data/artifacts:/data/artifacts
      - ./data/mlmodel/hate_speech_detector:/data/best_model/model
    networks:
      - app-network
  flask:
    env_file:
      - .env.flask.dev
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "80:80"
    volumes:
      - ./data/cv:/data/cv
      - ./data/mlmodel:/data/mlmodel
    networks:
      - app-network
  gradio:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    ports:
      - "7860:7860"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
